# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
# Configure db here
# machine:
  # services:
  #   neo4j
  # environment:
  #   NEO4J_VERSION:
  #     "3.5.3"
  # pre:
  #   - sudo sed -i "s|dbms.security.auth_enabled=true|dbms.security.auth_enabled=false|g" /etc/neo4j/neo4j-server.properties
  # post:
  #   - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  #   - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  #   - neo4j-community-$NEO4J_VERSION/bin/neo4j start
  # environment:
  #   # Add the latest neo4j binaries to the path.
  #   PATH: /usr/lib/neo4j/latest/bin/:$PATH

  # pre:
  #   - sudo sed -i "s|dbms.security.auth_enabled=true|dbms.security.auth_enabled=false|g" /etc/neo4j/neo4j-server.properties
  #   # Start neo4j.
  #   - sudo service neo4j start

defaults: &defaults
  docker:
    - image: circleci/node:11.9.0-stretch
      environment:
        ADMINISTRATOR_NAME: Shop Inc
    - image: neo4j:3.5.3
  working_directory: ~/identity-management

install_npm_packages: &install_npm_packages
  run:
    name: Install Npm Dependencies
    command: yarn install

attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/identity-management

persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
    root: .
    paths: .

filters: &filters
  filters:
    branches:
      only:
        - develop
        - master

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - *install_npm_packages

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - *persist_to_workspace

  test_and_report:
    <<: *defaults
    steps:
      - *attach_workspace
      - *install_npm_packages
      - run:
          name: Run identity-management lint test
          command: yarn lint
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for neo4j to be ready
          command: dockerize -wait tcp://localhost:7474/ -timeout 1m
      # - run:
      #     name: Wait for neo4j to be ready
      #     command: dockerize -wait tcp://localhost:7687 -timeout 1m
      # - run:
      #     name: Wait for neo4j to be ready
      #     command: dockerize -wait  --publish=7474:7474 --publish=7687:7687 --volume=$HOME/neo4j/data:/data neo4j:3.5 -timeout 1m
      - run:
          name: Run identity-management test suites
          command:
            yarn test
      - *persist_to_workspace

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - checkout_code
      - test_and_report:
          requires:
            - checkout_code
