export default [
  'DEBUG',
  'GRPC_SERVER_HOST',
  'GRAPH_DB_USER',
  'GRAPH_DB_PASSWORD',
  'GRAPH_DB_PROTOCOL',
  'GRAPH_DB_HOST',
  'GRAPH_DB_PORT',
  'GRAPH_DB_NAME',
  'GOOGLE_CLIENT_ID',
  'ADMINISTRATOR_EMAIL',
  'ADMINISTRATOR_NAME',
  'SECRET_KEY',
];
